#ifndef _FLASH_TOOL_ERROR_CODE_DEF_H
#define _FLASH_TOOL_ERROR_CODE_DEF_H
typedef enum {
    //<8000 is defined by brom.dll mtk_status.h
    FT_SUCCESS = 8000,
    FT_EXCEPTION = 8001,
    FT_USER_PRESS_STOP_BUTTON = 8002,
    //SCAN USB ERROR
    FT_FIND_USB_ERROR = 8100,
    FT_FIND_GADGET_USB_ERROR = 8101,
    //PLATFORM ERROR
    FT_DL_PLATFORM_ERROR = 8200,
    //BACKUP->FORMAT->DL->RESTORE ERROR
    FT_UPGRADE_FOLDER_OVERLAPPED = 8300,
    FT_UPGRADE_FOLDER_NOT_EXSIT = 8301,
    FT_UPGRADE_DIR_CREATE_FAIL = 8302,
    FT_UPGRADE_FILE_CORRUPTED = 8303,
    FT_UPGRADE_FILE_NOT_EXSIT = 8304,
    FT_UPGRADE_BACKUP_ROM_NOT_EXSIT = 8305,
    FT_OTP_FILE_NOT_WORD_ALIGN = 8306,
    FT_UPGRADE_LAYOUT_CHANGED = 8307,

    //Others
    FT_FIND_NVRAM_ERROR     = 8400,
    FT_INVALID_FORMAT_ADDR_ERROR = 8401,
    FT_FIND_PLATFORM_ERROR = 8402,
    FT_FIND_STORAGE_ERROR = 8403,
    FT_FIND_IMAGEMAP_ERROR = 8404,
    FT_INVALIDE_SESSION_KEY = 8405,
    FT_INVALID_MEM_INFO = 8406,
    FT_SAVE_FILE_ERROR = 8407,
    FT_LOAD_DA_ERROR = 8408,
    FT_GET_DA_INFO_ERROR = 8409,
    FT_LOAD_CERT_ERROR = 8410,
    FT_LOAD_AUTH_ERROR = 8411,
    FT_GET_RESTORE_ITEM_ERROR = 8412,
    FT_RESTORE_ERROR = 8413,
    FT_FILE_FOLDER_IS_NOT_EXIST = 8414,
    FT_FILE_IS_NOT_EXIST = 8415,
    FT_FLASHTOOL_ERROR_CHKSUM_FAIL = 8416,
    FT_FLASHTOOL_INVALIDE_SCATTER = 8417,
    FT_LOAD_TRANSLATION_FILE_FAIL = 8418,
    FT_RPMB_WRITTEN_BEFORE_DL = 8419,
    FT_SCATTER_COMBO_PARTSIZE_CHECK_ERR = 8420
} FLASH_TOOL_RESULT;
#endif //_FLASH_TOOL_ERROR_CODE_DEF_H
