
#include "constString.h"
#include <QTextCodec>
#include <QObject>

QString strEngVec[] = {
    QObject::tr("Failed to Start Updater.exe!"),
    QObject::tr("Crashed!"),
    QObject::tr("Please load a DA before execution."),
    QObject::tr("Please load a scatter file before execution."),
    QObject::tr("Time out!"),
    QObject::tr("Unknow Error!"),
    QObject::tr("Open Download Agent File"),
    QObject::tr("Bin File (*.bin)"),
    QObject::tr("Open Scatter File"),
    QObject::tr("Map File (*.txt *.xml);;All Files(*.*)"),
    QObject::tr("Download Ok"),
    QObject::tr("The chip is not supported by flash tool! Please check if it is valid."),
    QObject::tr("The storage type is not supported by flash tool! Please check if it is valid."),
    QObject::tr("Please select one ROM at least before execution."),
    QObject::tr("Form&at"),
    QObject::tr("Format Ok"),
    QObject::tr("Your Software is up to date now."),
    QObject::tr("(Runtime Trace Mode)"),
    QObject::tr("(Advanced Mode)"),
    QObject::tr("(Mark NAND Bad Blocks Mode)"),
    QObject::tr("Warning: The program is running, still continue?"),
    QObject::tr("Exit"),
    QObject::tr("Please load Preloader or DSP_BL before execution."),
    QObject::tr("Memory &Test"),
    QObject::tr("Select one item at least"),
    QObject::tr("Memory Test Ok"),
    QObject::tr("Save file as..."),
    QObject::tr("Open OTP file..."),
    QObject::tr("No com port detected."),
    QObject::tr("Find com port failed."),
    QObject::tr("Failed to register USB device notification."),
    QObject::tr("&Parameter"),
    QObject::tr("Write OTP Ok"),
    QObject::tr("Read OTP Ok"),
    QObject::tr("&Readback"),
    QObject::tr("Readback Ok"),
    QObject::tr("Save File"),
    QObject::tr("Please add a read back item before execution."),
    QObject::tr("&Write Memory"),
    QObject::tr("Write Memory Ok"),
    QObject::tr("&Download"),
    QObject::tr("&OK"),
    QObject::tr("&Cancel"),
    QObject::tr("&Yes"),
    QObject::tr("&No"),
    QObject::tr("Open CERT File..."),
    QObject::tr("Open AUTH File..."),
    QObject::tr("Authentication File (*.auth);;All Files(*.*)"),
    QObject::tr("Cert File (*.cert);;All Files(*.*)"),
    QObject::tr("Select Log Folder..."),
    QObject::tr("Please load a certification file before execution."),
    QObject::tr("Cerfitication OK"),
    QObject::tr("&Help"),
    QObject::tr("W&elcome"),
    QObject::tr("Show Welcome"),
    QObject::tr("Hide Welcome"),
    QObject::tr("Like Mota"),
    QObject::tr("Format All + Download"),
    QObject::tr("Firmware Upgrade"),
    QObject::tr("Download Only"),
    QObject::tr("Address or length bytes not align"),
    QObject::tr("One Day"),
    QObject::tr("One Week"),
    QObject::tr("One Month"),
    QObject::tr("Three Month"),
    QObject::tr("OTP Write Setting"),
    QObject::tr("OTP Read Setting"),
    QObject::tr("&Brom Adapter"),
    QObject::tr("Open Download Data File"),
    QObject::tr("File size is zero"),
    QObject::tr("No memory"),
    QObject::tr("Load data failed."),
    QObject::tr("BROM download OK."),
    QObject::tr("BROM jump OK."),
    QObject::tr("Partition Table changed, please try to use Firmware upgrade or Format All + download scene instead."),
    QObject::tr("Unlock Boot-loader"),
    QObject::tr("(Security Mode)"),
    QObject::tr("Unlock bootloader?\n\n"
                "If you unlock the bootloader, you will be able to install custom operating system software on this phone.\n\n"
                "A custom OS is not subject to the same testing as the original OS, and can cause your phone and installed applications to stop working properly.\n\n"
                "To prevent unauthorized access to your personal data, unlocking the bootloader will alaso delete all personal data from your phone (a \"factory data reset\")\n\n"
                "1. The data partition will be fully erased, please backup your personal data before unlocking.\n\n"
                "2. The device may not be able to boot up successfully after erasing data partition, please download customized images after unlocking or enter recovery mode to do \"wipe data\\factory reset\" operation.\n\n"
                "Yes: Unlock bootloader(may void warranty)\n"
                "No:  Do not unlock bootloader."),
    QObject::tr("Not a signed image or not an unlock secro image."),
    QObject::tr("Not allowd load unlock secro image."),
    QObject::tr("Decrpyt download data failed."),
    QObject::tr("&Report"),
    QObject::tr("Unable to launch Qt Assistant."),
    QObject::tr("Please select the write file first!"),
    QObject::tr("Please select the read file first!"),
    QObject::tr("The scatter file cannot find, please make sure the file is exist before download."),
    QObject::tr("&SCI Download"),
    QObject::tr("&Clone Download"),
    QObject::tr("Please load SCI Scatter file before download!"),
    QObject::tr("Please select readback folder before readback."),
    QObject::tr("Please select restore folder before restore!"),
    QObject::tr("Please check the load image file is correct or not?"),
    QObject::tr("Smart Phone Flash Tool"),
    QObject::tr("About Smart Phone Flash Tool"),
    QObject::tr("DA and Library Info"),
    QObject::tr("Copyright (c) 2001-2026, MediaTek Inc. All rights reserved."),
    QObject::tr("Comment: [Customer Release] "),
    QObject::tr("Comment: [Internal Release] "),
    QObject::tr("Build: "),
    QObject::tr("Build-Date: "),
    QObject::tr("Software Update"),
    QObject::tr("Checking for update..."),
    QObject::tr("<html><head/><body><p>A new version of Flash tool is availabel</p></body></html>"),
    QObject::tr("&Remind Me Later"),
    QObject::tr("&Install Update"),
    QObject::tr("Lacking of update files.\nPlease re-install the tool or contact the tool owner."),
    QObject::tr("Start update tool failed.\nPlease re-install the tool or contact the tool owner."),
    QObject::tr("Update tool failed.\nPlease re-install the tool or contact the tool owner."),    
    QObject::tr("Encrypt"),
    QObject::tr("Please enter password:"),
    QObject::tr("Incorrect Password! Try again!"),
    QObject::tr("Flash Phone have risk.\nContinue?"),
    QObject::tr("Continue"),
    QObject::tr("Warning"),
    QObject::tr("Device &Test"),
    QObject::tr("Device Test Ok"),
    QObject::tr("Please add one readback item before export."),
    QObject::tr("Select Log Path"),
	QObject::tr("Update"),
	QObject::tr("Please close other Flash Tool which is running before installing update."),
    QObject::tr("DRAM Repair"),
    QObject::tr("DRAM repair address written done"),
    QObject::tr("DRAM repair address is NOT written."),
    QObject::tr("Operation failed!\nPlease select at least one download scene or contact tool owner."),
    QObject::tr("Notice that  90% of life time for storage in your device has passed, please change to use new device as soon as possible.\nDo you want to continue anyway?"),
    QObject::tr("Please provide pgpt partition before download when skip_pmt_operate is true in scatter file."),
    QObject::tr("Please pgpt partition MUST be selected before download when skip_pmt_operate is true in scatter file.")
};

const QString strCHString[]={
    "��������ʧ�ܣ�",
    "������",
    "ִ��ǰ�����DA�ļ���",
    "ִ��ǰ�����scatter�ļ�.",
    "��ʱ��",
    "δ֪����",
    "��DA�ļ�",
    "Bin File (*.bin)",
    "��scatter�ļ�",
    "Map File (*.txt *.xml)",
    "�������",
    "Flash Tool��֧�ָ�оƬ�������Ƿ���ЧоƬ.",
    "��֧�ֵĴ洢���ͣ�����洢�����Ƿ���Ч",
    "������ѡ��һ��ROM����",
    "��ʽ��(&A)",
    "��ʽ�����",
    "��������Ѿ������°汾�ˡ�",
    "(����ʱ����ģʽ)",
    "(�߼�ģʽ)",
    "(���NAND����ģʽ)",
    "���棺�������������У��Ƿ������",
    "�˳�",
    "�����Preloader��DSP_BL",
    "�ڴ����(&T)",
    "������ѡ��һ��������",
    "�ڴ�������",
    "����Ϊ...",
    "��OTP�ļ�",
    "δ��⵽����",
    "���Ҵ���ʧ�ܡ�",
    "ע��USB�豸֪ͨʧ��",
    "����(&P)",
    "дOTP���",
    "��OTP���",
    "�ض�(&R)",
    "�ض����",
    "�����ļ�",
    "������һ���ض���",
    "д�ڴ�(&W)",
    "д�ڴ����",
    "����(&D)",
    "ȷ��(&O)",
    "ȡ��(&C)",
    "��(&Y)",
    "��(&N)",
    "��CERT�ļ�",
    "��AUTH�ļ�",
    "Authentication File (*.auth);;All Files(*.*)",
    "Cert File (*.cert);;All Files(*.*)",
    "ѡ����־�ļ�...",
    "����ǰ�����һ����֤�ļ�",
    "��֤���",
    "����(&H)",
    "��ӭ(&E)",
    "��ʾ��ӭҳ��",
    "���ػ�ӭҳ��",
    "��MOTA",
    "ȫ����ʽ��������",
    "�̼�����",
    "����",
    "��ַ�򳤶��ֽ�û�ж���",
    "һ��",
    "һ��",
    "һ��",
    "����",
    "OTPд����",
    "OTP������",
    "&BROM������",
    "�����������ļ�",
    "�ļ���СΪ0",
    "�ڴ治��",
    "���ݼ���ʧ��",
    "BROM���سɹ�",
    "BROM��ת�ɹ�",
    "�����б仯���볢��ʹ��Firmware upgrade����Format All + Download�������ء�",
    "����Boot-loader",
    "(��ȫģʽ)",
    "���ݷ���������ȫ��������������ʱ���ȱ��ݺø�������.\n"
    "���ݲ������豸����û���������������ڽ����������Զ����Ӱ���ļ����߽���ָ�ģʽ������\"����/�ָ���������\"����",
    "δǩ�µĻ��߲��ǽ�����ӳ���ļ�",
    "���������ؽ⿪�İ�ȫӳ���ļ�",
    "���ݽ���ʧ��.",
    "���ʹ��󱨸�(&R)",
    "�޷�����qt����",
    "��ָ��OTPд�ļ�·��",
    "��ָ��OTP���ļ�·��",
    "�޷��ҵ�Ҫ���ص��ļ���������֮ǰȷ���ļ����ڡ�",
    "&SCI ����",
    "&Clone ����",
    "��������ǰ����SCI Scatter�ļ�!",
    "���ڻض�֮ǰ�趨Ҫ�����·��!",
    "���ڻ�д֮ǰѡ����Ҫ��д���ļ���·��!",
    "������ص��ļ��Ƿ���ȷ?",
    "�����ֻ����ع���",
    "���������ֻ����ع���",
    "DA �� Library ��Ϣ",
    "��Ȩ 2001-2026 �����Ƽ����޹�˾����������Ȩ����",
    "��ע [�ͻ��汾]",
    "��ע��[�ڲ�����]",
    "������",
    "�������ڣ� ",
    "��������",
    "�����°汾...",
    "<html><head/><body><p>һ���µ�Flash Tool �汾����</p></body></html>",
    "�´�����(&R)",
    "��װ����(&I)",
    "ȱ�ٱ�Ҫ�ĸ����ļ����¸���ʧ�ܣ�\n�����°�װFlash Tool����ϵTool Owner��",
    "������������ʧ�ܣ�\n�����°�װFlash Tool����ϵTool Owner��",    
    "����ʧ�ܣ�\n�����°�װFlash Tool����ϵTool Owner��",        
    "����",
    "���������룺",
    "������������ԣ�",
    "ˢ���з��գ���ȷ���Ƿ����?",
    "����",
    "����",
    "�豸����(&T)",
    "�豸�������",
    "���ڵ���ǰ����һ���ض���",
    "ѡ����־Ŀ¼",
	"����",
    "����֮ǰ���ȱչ������򿪵�Flash Tool",
    "DRAM�޸�",
    "�ɹ�д��DRAM�޸���ַ",
    "δ�ɹ�д��DRAM�޸���ַ",
    "����ʧ�ܣ�\n������ѡ��һ��download scene����ϵTool Owner��",
    "�洢�����������ڵ�90%�Ѿ����ģ��뾡��������豸��\n�������Ƿ������",
    "scatter�ļ���skip_pmt_operate����Ϊtrueʱ������ʱ���ṩpgpt������",
    "scatter�ļ���skip_pmt_operate����Ϊtrueʱ������ʱpgpt��������ѡ��"
};

const QString strTWString[]={
    "���Ӹ���ʧ����",
    "������",
    "����ǰՈ���dDA�ļ���",
    "����ǰՈ���dscatter�ļ�.",
    "���r��",
    "δ֪�e�`��",
    "���_DA�ļ�",
    "Bin File (*.bin)",
    "���_�����ļ�",
    "Map File (*.txt *.xml)",
    "���d���",
    "Flash Tool��֧��ԓоƬ��Ո�z���Ƿ���ЧоƬ.",
    "��֧�ֵĴ惦��ͣ�Ո�z��惦����Ƿ���Ч",
    "Ո�����x��һ��ROM���",
    "��ʽ��(&A)",
    "��ʽ�����",
    "���ܛ�w�ѽ������°汾�ˡ�",
    "(�\�Еr��ۙģʽ)",
    "(�߼�ģʽ)",
    "(��ӛNAND�ĉKģʽ)",
    "���棺���������\���У��Ƿ��^�m��",
    "�˳�",
    "Ո���dPreloader��DSP_BL",
    "�ȴ�yԇ(&T)",
    "������ѡ��һ��������",
    "�ڴ�yԇ���",
    "�����...",
    "���_OTP�ļ�",
    "δ�z�y������",
    "���Ҵ���ʧ����",
    "�]��USB�O��֪ͨʧ��",
    "����(&P)",
    "��OTP���",
    "�xOTP���",
    "���x(&R)",
    "���x���",
    "�����ļ�",
    "Ո����һ�����x�",
    "���ȴ�(&W)",
    "���ڴ����",
    "���d(&D)",
    "�_��(&O)",
    "ȡ��(&C)",
    "��(&Y)",
    "��(&N)",
    "���_CERT�ļ�",
    "���_AUTH�ļ�",
    "Authentication File (*.auth);;All Files(*.*)",
    "Cert File (*.cert);;All Files(*.*)",
    "�x�����I�ļ�...",
    "�\��ǰՈ���dһ����C�ļ�",
    "��C���",
    "����(&H)",
    "�gӭ(&E)",
    "�@ʾ�gӭ���",
    "�[�ؚgӭ���",
    "�MOTA",
    "ȫ����ʽ�������d",
    "�̼�����",
    "���d",
    "��ַ���L���ֹ��]�Ќ��R",
    "һ��",
    "һ��",
    "һ��",
    "����",
    "OTP���O��",
    "OTP�x�O��",
    "&BROM�m����",
    "���_���d�����ļ�",
    "�ļ���С��0",
    "�ȴ治��",
    "�������dʧ��",
    "BROM ���d�ɹ�",
    "BROM ���D�ɹ�",
    "�օ^��׃����Ո�Lԇʹ��Firmware upgrade����Format All + Download�������d��",
    "���iBoot-loader",
    "(��ȫģʽ)",
    "1. �����օ^������ȫ������Ո�ڽ��i֮ǰ��ݺ��˔���.\n"
    "2. �����������O����ܟo���������ӣ�Ո�ڽ��i�����d�Զ��xӰ���ļ������M���ԭģʽ\"��������/�֏ͳ��S�O��\"",
    "δ���µĻ��߲��ǽ��i��ӳ���ļ�",
    "�����S���d���_�İ�ȫӳ���ļ�",
    "��������ʧ��.",
    "�l���e�`���(&R)",
    "�o������qt����",
    "Ոָ��OTP���ļ�·��",
    "Ոָ��OTP�x�ļ�·��",
    "�o���ҵ�Ҫ���d���ļ���Ո�����d֮ǰ�_�JҪ���d���ļ��Ƿ���ڡ�",
    "&SCI ���d",
    "&Clone ���d",
    "Ո�����d֮ǰ�ȼ��dSCI Scatter�ļ�!",
    "Ո�ڻ��x֮ǰ�O��Ҫ�����·��!",
    "Ո�ڻ،�֮ǰ�x����Ҫ�،����ļ��A·��!",
    "Ո�z����d���ļ��Ƿ����_?",
    "�ǻ����֙C���d����",
    "�P��ǻ����֙C���d����",
    "DA �� Library ӍϢ",
    "��� 2001-2026, �l�Ƽ����޹�˾���������Й�����",
    "���] [�͑��汾]",
    "���]��[�Ȳ��l��]",
    "������",
    "�������ڣ�",
    "ܛ�w����",
    "���z�y...",
    "<html><head/><body><p>A new version of Flash tool is availabel</p></body></html>",
    "��������(&R)",
    "���b����(&I)",
    "ȱ�ٱ�Ҫ�ĸ����ļ����¸���ʧ����\nՈ���°��bFlash Tool���MTool Owner��",
    "������������ʧ����\nՈ���°��bFlash Tool���MTool Owner��",    
    "����ʧ����\nՈ���°��bFlash Tool���MTool Owner��",        
    "����",
    "Ոݔ���ܴa��",
    "�ܴa�e�`��Ո��ԇ��",
    "ˢ�C���L�U��Ո�_�J�Ƿ��^�m?",
    "�^�m",
    "����",
    "�O��yԇ(&T)",
    "�O��yԇ���",
    "Ո�ڌ���ǰ����һ�����x�",
    "�x�����IĿ�",
	"����",
    "����֮ǰՈ���P�]�������_��Flash Tool",
    "DRAM�ޏ�",
    "�ɹ�����DRAM�ޏ͵�ַ",
    "δ�ɹ�����DRAM�ޏ͵�ַ",
    "����ʧ����\nՈ�����x��һ�Ndownload scene���MTool Owner��",
    "�惦���|�����L�ڵ�90%�ѽ����ģ�Ո�M����Q���O�䡣\nՈ�����Ƿ��^�m��",
    "scatter�ļ���skip_pmt_operate�O�Þ�true�r�����d�rՈ�ṩpgpt�օ^��",
    "scatter�ļ���skip_pmt_operate�O�Þ�true�r�����d�rpgpt�օ^����x��"
};

const QString test = QObject::tr("DownloadTest");
const QString exitInfo = QObject::tr("The application is running, are you sure to exit?");

QString LoadQString(Language_Tag languageID, int strID)
{
    QByteArray str;

    switch(languageID)
    {
    case LANGUAGE_ENGLISH:
        return strEngVec[strID];

    case LANGUAGE_ZH_CHINESE:
        str = strCHString[strID].toLatin1();
        return QTextCodec
                ::codecForName("GBK")->toUnicode(str.data());

    case LANGUAGE_TW_CHINESE:
        str = strTWString[strID].toLatin1();
        return QTextCodec
                ::codecForName("GBK")->toUnicode(str.data());
    }

    return "";
}
